version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: health_declaration_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # NestJS Backend
  backend:
    build:
      context: ./health_declaration_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/health_declaration_db
      NODE_ENV: production
      PORT: 5000
      CORS_ORIGIN: http://frontend:3000
    container_name: health_declaration_backend
    image: manhpd12/health_declaration_backend:latest
    depends_on:
      - mysql
    networks:
      - app-network

  # React Frontend
  frontend:
    build:
      context: ./health_declaration_frontend
      dockerfile: Dockerfile
    container_name: health_declaration_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    image: manhpd12/health_declaration_frontend:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
